a2ms:
  container_name: a2ms
  image: endaaman/a2ms
  environment:
    VIRTUAL_HOST: a2ms.med.hokudai.ac.jp,a2ms.dev
    API_HOST: a2ms-api
  external_links:
   - a2ms-api
  volumes:
    - /var/shared/a2ms:/var/shared/a2ms

