module.exports = (Vue)->
    (require './trailing_slash') Vue
    (require './i18n') Vue
    (require './rule') Vue
    (require './href') Vue
    (require './title') Vue
    (require './scroll') Vue
    (require './loader') Vue
    (require './meta') Vue
    (require './ga') Vue
